### ISSUE TITLE
Unit tests are only running Tests.dll for net472

### ISSUE THREAD

**Issue by flcdrg** [Fody/NullGuard#263]
The current appveyor.yml test pattern is only matching Tests.dll (Tests project) and AppVeyor only seems to run .NET Framework target platform.

Modifying the wildcard pattern adds extra projects, but doesn't run non-net472 assemblies (such as is planned to be added by #244 

Using a script to change how tests are run in AppVeyor seems to get further, but is resulting in some weird errors. eg.

```text
System.TypeInitializationException : The type initializer for 'AssemblyWeaver' threw an exception.
---- System.Exception : The files have difference peverify results.

AfterOutput:
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : ClassWithExplicitInterface::System.IComparable<System.String>.CompareTo] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : ClassWithExplicitInterface+ClassWithExplicitPublicInterface::System.IComparable<System.String>.CompareTo] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : ClassWithImplicitInterface::CompareTo] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : ClassWithImplicitInterface+ClassWithImplicitPublicInterface::CompareTo] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : ClassWithPrivateMethod::SomePrivateMethod] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClass`1[T]::get_NonNullProperty] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClass`1[T]::set_NonNullProperty] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClass`1[T]::NonNullMethod] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClass`1[T]::GenericMethod[U]] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClass`1[T]::GenericMethodReturnsParameter[U]] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClass`1[T]::GetThing] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClass`1[T]::GetThing2] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClass`1+<GetThing2>d__12[T]::MoveNext] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClassFactory::get_Integer] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClassFactory::get_Struct] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClassFactory::get_Object] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClassWithReferenceTypeConstraints`1[T]::get_NonNullProperty] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClassWithReferenceTypeConstraints`1[T]::set_NonNullProperty] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClassWithReferenceTypeConstraints`1[T]::NonNullMethod] Unable to resolve token.(Error: 0x80131869)
[IL]: Error: [C:\projects\nullguard\Tests\bin\Release\netcoreapp2.2\fodytemp\AssemblyToProcess.dll : GenericClassWithReferenceTypeConstraints`1[T]::GenericMethod[U]] Unable to resolve token.(Error: 0x
```

**Comment by mikernet** [comment]
I fixed most of the problem, there are now only a handful of failing tests for explicit mode. Let me see if I can figure out the remaining issues and I'll push what I have.

**Comment by mikernet** [comment]
Perhaps "fixed" is the wrong word - I just added `0x80131869` to the list of `ignoreCodes` but I don't actually know what the code means or if there's a way to fix it instead of ignoring it...the tests seem to be behaving as expected though.

@tom-englert @SimonCropp I don't really know when it is safe to ignore these codes and when it isn't, do you have any input into this?

**Comment by tom-englert** [comment]
@mikernet https://docs.microsoft.com/en-us/archive/blogs/yizhang/interpreting-hresults-returned-from-netclr-0x8013xxxx
0x80131869 is caused by xunit runner using shadow copies of references that are not in the same folder as the testee assembly.
Fixed here: beb2c5c

**Comment by flcdrg** [comment]
Still getting a bunch of  `Unable to resolve token.(Error: 0x80131869)` on AppVeyor (but not locally)
